### PR TITLE
Add missing API to typescript definition

### PR DESCRIPTION
**Pull request by pszalanski**
This PR includes the following changes:
* Add `resetId()` to `Node`, to reset the ID counter
* add "npm prepare" to use rete as git dependency
* Add missing type definitions to `engine.d.ts`

### CODE REVIEW

**Comment by Ni55aN** [comment]
How to disable the "prepare" for packages from NPM?

**Comment by pszalanski** [comment]
Hm, I am not sure if the "prepare" step is run, if it is installed packaged from npm.

I don't have *any* experience releasing packages to npm. And I couldn't find anything on Google.

**Comment by Ni55aN** [comment]
It may take more time to install from npmjs, and some may only install packages from "dependencies"

**Comment by pszalanski** [comment]
Okay, if you are sure that it is run in that case. The alternative would be to check the build artifacts into git, which many libs do.

I am really unsure what to do here. We need that script to use your package from our fork, because although you react to requests in a really speedy manner (thanks for that), we cannot always depend on upstream to implement the changes we need and to wait for a new package release.

On the other hand, we have a good initial version up and running and might not depend so much on the current state of `retejs`.

If you want, I could prepare a new PR without the "prepare" script.

**Comment by Ni55aN** [comment]
I can to cherry-pick some commits (exclude unnecessary Merge commits and so on). 
What is the purpose of `resetId()`?

**Comment by Ni55aN** [comment]
@tzahari ok, I'll accept this

**Comment by Ni55aN** [comment]
@pszalanski I merged two commits, others are not necessary (for example, commits on Nov 20 have been merged earlier)

**Pull request closed without merging**
